services:
  # ==========================
  # RabbitMQ (mensageria)
  # ==========================
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta do broker
      - "15672:15672"  # Painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app-network

  # ==========================
  # Gateway API (.NET)
  # ==========================
  gateway-api:
    build:
      context: ./backend/gatewayApi
      dockerfile: Dockerfile
    container_name: gateway-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

  # ==========================
  # User API (.NET)
  # ==========================
  user-api:
    build:
      context: ./backend/userApi
      dockerfile: Dockerfile
    container_name: user-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

  # ==========================
  # Currency API (.NET)
  # ==========================
  currency-api:
    build:
      context: ./backend/currencyApi
      dockerfile: Dockerfile
    container_name: currency-api
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network
    volumes:
      - currency-data:/app/data


  # ==========================
  # Wallet API (.NET)
  # ==========================
  wallet-api:
    build:
      context: ./backend/walletApi
      dockerfile: Dockerfile
    container_name: wallet-api
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

  # ==========================
  # Chatbot API (.NET)
  # ==========================
  chatbot-api:
    build:
      context: ./backend/chatbotApi
      dockerfile: Dockerfile
    container_name: chatbot-api
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - app-network

  # ==========================
  # Frontend (React)
  # ==========================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GATEWAY_URL=http://localhost:5000
    depends_on:
      - gateway-api
    networks:
      - app-network

  # ==========================
  # Mobile (Flutter web build)
  # ==========================
  # mobile:
  #   build:
  #     context: ./mobile
  #     dockerfile: Dockerfile
  #   container_name: mobile
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - gateway-api
  #   networks:
  #     - app-network

# ==========================
# Rede compartilhada
# ==========================
networks:
  app-network:
    driver: bridge


volumes:
  currency-data: